apiVersion: apps/v1
kind: Deployment
metadata:
  name: presidio-nl-v2
  namespace: presidio-nl-v2
  labels:
    app: presidio-nl-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presidio-nl-v2
  template:
    metadata:
      labels:
        app: presidio-nl-v2
    spec:
      serviceAccountName: presidio-nl-v2
      securityContext: {}
      containers:
      - name: presidio-nl-v2
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        image: ghcr.io/mwest2020/presidio-nl-v2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8080"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        - name: TRANSFORMERS_CACHE
          value: "/app/models"
        - name: HF_HOME
          value: "/app/models"
        - name: TORCH_HOME
          value: "/app/models"
        - name: STORAGE_DIR
          value: "/app/storage"
        - name: MAX_STORAGE_TIME
          value: "3600"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "4Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "1500m"
        volumeMounts:
        - name: storage
          mountPath: /app/storage
        - name: models
          mountPath: /app/models
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: presidio-nl-v2-storage
      - name: models
        emptyDir: {} 