# Staging environment values for OpenAnonymiser
replicaCount: 1

image:
  repository: mwest2020/openanonymiser
  tag: dev  # Always use latest dev tag for staging
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    # Staging: SSL disabled for easier testing
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "staging-api.openanonymiser.commonground.nu"
      paths:
        - path: /
          pathType: Prefix
  tls: []  # No SSL for staging

resources:
  limits:
    cpu: 1000m  # Lower resources for staging
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 2Gi

persistence:
  enabled: true
  storageClass: "nfs"
  size: 10Gi  # Smaller storage for staging
  # Staging data directory
  # - SQLite database (/app/data/openanonymiser.db)
  # - Test files (/app/data/temp/)

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Staging-specific environment variables
env:
  LOG_LEVEL: debug  # More verbose logging for staging
  DEBUG: true

# Network policy for staging (more permissive)
networkPolicy:
  enabled: false  # Disabled for easier testing