# Default values for presidio-nl-v2
replicaCount: 1

image:
  repository: mwest2020/openanonymiser
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "4G"
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
    - host: "api.openanonymiser.commonground.nu"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: openanonymiser
              port:
                number: 8080
  tls:
    - hosts:
        - "api.openanonymiser.commonground.nu"
      secretName: "openanonymiser-tls"

resources:
  limits:
    cpu: 1500m
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 4Gi

persistence:
  enabled: true
  storageClass: "nfs"
  size: 25Gi

networkPolicy:
  enabled: true
  allowedNamespaces:
    - presidio
    - default

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

app:
  debug: false
  logLevel: "info"
  api:
    host: "0.0.0.0"
    port: 8080
    internalOnly: false
  storage:
    cleanupInterval: 3600 