apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: presidio-nl-v2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MWest2020/Presidio-NL_v2.git
    targetRevision: HEAD
    path: charts/presidio-nl-v2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: presidio-nl-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas # Ignore replica count changes from HPA 