apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openanonymiser-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ConductionNL/OpenAnonymiser.git
    targetRevision: main  # ← Production wijst naar main branch
    path: charts/openanonymiser
  destination:
    server: https://kubernetes.default.svc
    namespace: openanonymiser  # ← Production namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true