apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openanonymiser.fullname" . }}
  labels:
    app: {{ include "openanonymiser.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "openanonymiser.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "openanonymiser.name" . }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "openanonymiser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.app.logLevel | quote }}
            - name: DEBUG
              value: {{ .Values.app.debug | quote }}
            - name: API_HOST
              value: {{ .Values.app.api.host | quote }}
            - name: API_PORT
              value: {{ .Values.app.api.port | quote }}
            - name: INTERNAL_ONLY
              value: {{ .Values.app.api.internalOnly | quote }}
            - name: STORAGE_CLEANUP_INTERVAL
              value: {{ .Values.app.storage.cleanupInterval | quote }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: logs-volume
              mountPath: /app/logs
