{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "presidio-nl-v2.serviceAccountName" . }}
  labels:
    app: {{ include "presidio-nl-v2.name" . }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }} 